In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
X = pd.DataFrame(iris['data'], columns=iris['feature_names'])

In [5]:
y = pd.DataFrame(iris['target'], columns=['target'])

In [8]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

In [11]:
from sklearn.linear_model import SGDClassifier

In [12]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [13]:
# Logistic Regrssion 
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train['target'])

log_reg_pred = log_reg.predict(X_test)
print(confusion_matrix(log_reg_pred, y_test['target']))
print(classification_report(log_reg_pred, y_test['target']))

[[13  0  0]
 [ 0  6  0]
 [ 0  0 19]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00        19

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
# Decision Tree
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X_train, y_train['target'])

tree_clf_pred = tree_clf.predict(X_test)
print(confusion_matrix(tree_clf_pred, y_test['target']))
print(classification_report(tree_clf_pred, y_test['target']))

[[13  0  0]
 [ 0  6  2]
 [ 0  0 17]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.75      0.86         8
           2       0.89      1.00      0.94        17

    accuracy                           0.95        38
   macro avg       0.96      0.92      0.93        38
weighted avg       0.95      0.95      0.95        38



In [15]:
# Stocastic Gradient Descent
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train['target'])

sgd_clf_pred = sgd_clf.predict(X_test)
print(confusion_matrix(sgd_clf_pred, y_test['target']))
print(classification_report(sgd_clf_pred, y_test['target']))

[[13  1  0]
 [ 0  5  1]
 [ 0  0 18]]
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.83      0.83      0.83         6
           2       0.95      1.00      0.97        18

    accuracy                           0.95        38
   macro avg       0.93      0.92      0.92        38
weighted avg       0.95      0.95      0.95        38



In [16]:
def Scaler(data):
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data)
    return data_scaled
X_train_scaled = Scaler(X_train)
X_test_scaled = Scaler(X_test)

In [17]:
# Scaled Linear SVC
new_lin_svc = LinearSVC()
new_lin_svc.fit(X_train_scaled, y_train['target'])

new_lin_svc_pred = new_lin_svc.predict(X_test_scaled)
print(confusion_matrix(new_lin_svc_pred, y_test['target']))
print(classification_report(new_lin_svc_pred, y_test['target']))

[[13  0  0]
 [ 0  6  7]
 [ 0  0 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.46      0.63        13
           2       0.63      1.00      0.77        12

    accuracy                           0.82        38
   macro avg       0.88      0.82      0.80        38
weighted avg       0.88      0.82      0.80        38



In [18]:
# Linear SVC
lin_svc = LinearSVC()
lin_svc.fit(X_train, y_train['target'])

lin_svc_pred = lin_svc.predict(X_test)
print(confusion_matrix(lin_svc_pred, y_test['target']))
print(classification_report(lin_svc_pred, y_test['target']))

[[13  0  0]
 [ 0  6  2]
 [ 0  0 17]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.75      0.86         8
           2       0.89      1.00      0.94        17

    accuracy                           0.95        38
   macro avg       0.96      0.92      0.93        38
weighted avg       0.95      0.95      0.95        38



C:\Users\User\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [22]:
sns.set_style(style='darkgrid')

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score 
rnf_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1)
rnf_clf.fit(X_train, y_train)
y_pred = rnf_clf.predict(X_test)
#print(rnf_clf.oob_score_)
print(accuracy_score(y_pred, y_test))

C:\Users\User\AppData\Local\Temp/ipykernel_17564/2441262785.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rnf_clf.fit(X_train, y_train)


0.9473684210526315


In [31]:
rnf_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1)
rnf_clf.fit(iris['data'], iris['target'])
for name, importance in zip(iris['feature_names'], rnf_clf.feature_importances_):
    print(name, importance)

sepal length (cm) 0.10172574384725312
sepal width (cm) 0.02421906894555867
petal length (cm) 0.43175906095164396
petal width (cm) 0.44229612625554415


In [14]:
# XGBoost
import xgboost

xgb = xgboost.XGBClassifier(max_depth=4,eta= 0.3,num_class = 3 ) 
xgb.fit(X_train, y_train['target'])

xgb_pred = xgb.predict(X_test)
print(confusion_matrix(xgb_pred, y_test['target']))
print(classification_report(xgb_pred, y_test['target']))

[11:38:21] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[13  0  0]
 [ 0 11  1]
 [ 0  1 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.92      0.92      0.92        12
           2       0.92      0.92      0.92        13

    accuracy                           0.95        38
   macro avg       0.95      0.95      0.95        38
weighted avg       0.95      0.95      0.95        38



C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


In [11]:
y_train

target
61        1
84        1
110       2
21        0
92        1
..      ...
140       2
32        0
143       2
104       2
79        1

[112 rows x 1 columns]